# Generated by Django 5.0.6 on 2024-06-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('website', models.URLField(max_length=255)),
                ('contact_no', models.CharField(max_length=15)),
                ('footer_message', models.TextField()),
                ('director_name', models.CharField(max_length=255)),
                ('msme_no', models.CharField(blank=True, max_length=255, null=True)),
                ('pin_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('district_code', models.CharField(max_length=10)),
                ('state_no_numeric', models.CharField(max_length=10)),
                ('state_code_alpha', models.CharField(max_length=10)),
                ('VAT_TIN', models.CharField(max_length=100)),
                ('CST_TIN', models.CharField(max_length=100)),
                ('C_Excise_Range', models.CharField(max_length=100)),
                ('Commissionerate', models.CharField(max_length=100)),
                ('C_Excise_Reg_No', models.CharField(max_length=100)),
                ('PLA_No', models.CharField(max_length=100)),
                ('Service_Tax_No', models.CharField(max_length=100)),
                ('Import_Export_Code', models.CharField(max_length=100)),
                ('ARN_No', models.CharField(max_length=100)),
                ('Export_House_No', models.CharField(max_length=100)),
                ('Udyog_Aadhar_No', models.CharField(max_length=100)),
                ('Vat_Tin_Date', models.DateField()),
                ('Cst_Tin_Date', models.DateField()),
                ('Subject_To', models.CharField(max_length=100)),
                ('Division', models.CharField(max_length=100)),
                ('GST_No', models.CharField(max_length=100)),
                ('ECC_No', models.CharField(max_length=100)),
                ('PAN_No', models.CharField(max_length=100)),
                ('CIN_NO', models.CharField(max_length=100)),
                ('Import_Export_Date', models.DateField()),
                ('ARN_Date', models.DateField()),
                ('LUT_NO', models.CharField(max_length=100)),
                ('LUT_Date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('creates_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
